#!/bin/sh
set -eu

MOD=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
PKG=umbrella-api
ARCH=all

command -v dpkg-deb >/dev/null || {
	echo "dpkg-deb is required" >&2
	exit 1
}

"$MOD/pkg/generate.sh"

VERSION=$(bump print --only-base "$MOD/bump.toml")
STAGE=$(mktemp -d)
trap 'rm -rf "$STAGE"' EXIT

mkdir -p "$STAGE/DEBIAN"
mkdir -p "$STAGE/usr/share/umbrella-api"
mkdir -p "$STAGE/usr/include/umbrella"

cp "$MOD/gen/schema.json" "$STAGE/usr/share/umbrella-api/schema.json"
cp "$MOD/gen/schema.h" "$STAGE/usr/include/umbrella/schema.h"

cat >"$STAGE/DEBIAN/control" <<EOF
Package: $PKG
Version: $VERSION
Section: devel
Priority: optional
Architecture: $ARCH
Maintainer: Tony B <tony@krakjn>
Homepage: https://github.com/krakjn/umbrella
Description: Shared umbrella schema (JSON + C header)
 Hello-world schema generated by the Python api module.
EOF

mkdir -p "$MOD/dist"
DEB="$MOD/dist/${PKG}_${VERSION}_${ARCH}.deb"
dpkg-deb --root-owner-group --build "$STAGE" "$DEB"
echo "built $DEB"
